apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  PORT: "8080"
  APP_ENV: "uat"
  LOG_LEVEL: "INFO"
  DOWNSTREAM_INVENTORY_URL: "http://inventory-service.uat.internal:9090"
